# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  requirements:
    desc: Write requirements.txt file
    cmds:
      - py -m pip freeze > requirements.txt
