# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  venv:
    desc: Create a virtual environment
    status:
      - test -d .venv
    cmds:
      - py -3.14.17
      - py -m venv .venv
  requirements:
    desc: Write requirements.txt file
    cmds:
      - py -m pip freeze > requirements.txt
  lint:
    desc: Lint the code
    cmds:
      - ruff check
  dev:
    desc: Run the development server
    cmds:
      - uv run fastapi dev
