name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.7'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
          version: '0.12.8'

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run tests
        run: |
          uv run pytest
